config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pins#index'
  resources :pins
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    has_many_attached :images
    validates :title, presence: true
    validates :caption, presence: true 

    #private
    #def image_type
    #    if images.attached? == false
    #       errors.add(:images, "can't be empty")
    #    end
    #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :caption, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<div class="container-fluid">
    <%= link_to 'Shopify Developer Intern Challenge', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "How it works and comments", home_about_path, class:"nav-link" %>
        </li>
    </div>
    
  </div>
</nav>

app/views/home/about.html.erb
<h1>How it works</h1>
<a style = "font-size: 150%">
This is a really simple application developed in ruby and rails, in the home page, you just select "New Image" and then you can complete the form with all the informations, including the image.
<br><br>
Going back to the home page, you can see all your uploaded images with the following buttons:
<br><br>
Show - You can see the image in a bigger size and the all the informations.<br>
Edit - You can edit all the informations of the upload, including the image.<br>
Destroy - You can completely delete the uploaded image.<br><br>

So this is a complete CRUD application. You can create using the new image, read using show, update using edit, and finally delete using destroy.<br>
<br>
<h2>Comments</h2><br>
Before doing the challenge, I searched and studied what Shopify uses, to be able to use the same technology, and this is why I did everything in ruby and rails.<br><br>
It was my first time using ruby and rails and I'm pretty satisfied with the result.
</a>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Image Repository</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class = "container">
    <br/>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br>
  <div class = "field">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true %>
  </div>
  <br>
  <div class="field">
    <%= form.label :caption %><br>
    <%= form.text_area :caption %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<b style = "font-size: 140%">
<% if current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  Sign up or Sign in to be able to add new images or edit and destroy it.<br>
  <%= link_to 'Sign up', new_user_registration_path %><br>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>
</b>
<h1>Images</h1>
<br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th style = "padding-left:20%">Caption</th>
      <th style = "padding-left:40%">First Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody style = "background-color: #dee2e6">
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.title %></td>
        <td style = "padding-left:20%;"><%= pin.caption %></td>
        <td style = "padding-left:40%"><%= image_tag(pin.images[0], style:'width:30%; height: auto') %></td>
        <td style = "font-size: 150%"><%= link_to 'Show', pin %></td>
        <% if current_user  %>
        <td style = "font-size: 150%"><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td style = "font-size: 150%"><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<b style = "font-size: 140%">
<%= link_to 'New Image', new_pin_path %>
</b>

app/views/pins/new.html.erb
<h1>New Image</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pin.title %>
</p>

<% (0...@pin.images.count).each do |image| %>
  <div style = "width: 100%; height: auto;">
  <%= image_tag(@pin.images[image], style:'width:40%; height: auto') %><br><br>
  </div>
<% end %>

<p>
  <strong>Caption:</strong>
  <%= @pin.caption %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>